# Generated by Django 5.0.1 on 2024-10-15 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Condominum',
            new_name='SellAppartment',
        ),
        migrations.RenameModel(
            old_name='GroundPlus',
            new_name='SellBuildings',
        ),
        migrations.RenameModel(
            old_name='Studio',
            new_name='SellCondominum',
        ),
        migrations.RenameModel(
            old_name='Buildings',
            new_name='SellGroundPlus',
        ),
        migrations.RenameModel(
            old_name='Villa',
            new_name='SellStudio',
        ),
        migrations.RenameModel(
            old_name='Appartment',
            new_name='SellVilla',
        ),
    ]
