# Generated by Django 5.0.1 on 2024-10-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renthouses',
            name='second_image',
            field=models.ImageField(upload_to='second_uploads/'),
        ),
    ]
